//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Math.Operations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Math.Operations.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperatorsConfiguration.json file is not present.
        /// </summary>
        internal static string FILENOTPRESENT {
            get {
                return ResourceManager.GetString("FILENOTPRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brackets are not in format.
        /// </summary>
        internal static string IMPROPERBRACKET {
            get {
                return ResourceManager.GetString("IMPROPERBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Expression.
        /// </summary>
        internal static string INVALIDEXPRESSION {
            get {
                return ResourceManager.GetString("INVALIDEXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation priority must be within 1 to 3.
        /// </summary>
        internal static string INVALIDPRIORITYEXCEPTION {
            get {
                return ResourceManager.GetString("INVALIDPRIORITYEXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation object can&apos;t be null.
        /// </summary>
        internal static string NULLOBJECTEXCEPTION {
            get {
                return ResourceManager.GetString("NULLOBJECTEXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient operands.
        /// </summary>
        internal static string OPERANDMISMATCH {
            get {
                return ResourceManager.GetString("OPERANDMISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator is not present.
        /// </summary>
        internal static string OPERATORNOTPRESENT {
            get {
                return ResourceManager.GetString("OPERATORNOTPRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Already present.
        /// </summary>
        internal static string OPERATORPRESENTEXCEPTION {
            get {
                return ResourceManager.GetString("OPERATORPRESENTEXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too big.
        /// </summary>
        internal static string OVERFLOWEXCEPTION {
            get {
                return ResourceManager.GetString("OVERFLOWEXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined Operation.
        /// </summary>
        internal static string UNDEFINEDOPERATION {
            get {
                return ResourceManager.GetString("UNDEFINEDOPERATION", resourceCulture);
            }
        }
    }
}
