//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Math.Operations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Math.Operations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        internal static string ADDITION {
            get {
                return ResourceManager.GetString("ADDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide.
        /// </summary>
        internal static string DIVIDE {
            get {
                return ResourceManager.GetString("DIVIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorial.
        /// </summary>
        internal static string FACTORIAL {
            get {
                return ResourceManager.GetString("FACTORIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogN.
        /// </summary>
        internal static string LogN {
            get {
                return ResourceManager.GetString("LogN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication.
        /// </summary>
        internal static string MULTIPICATION {
            get {
                return ResourceManager.GetString("MULTIPICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operatorsConfiguration.json.
        /// </summary>
        internal static string OPERATOR_FILE_PATH {
            get {
                return ResourceManager.GetString("OPERATOR_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string POWER {
            get {
                return ResourceManager.GetString("POWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precentage.
        /// </summary>
        internal static string PRECENTAGE {
            get {
                return ResourceManager.GetString("PRECENTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciprocal.
        /// </summary>
        internal static string RECIPROCAL {
            get {
                return ResourceManager.GetString("RECIPROCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction.
        /// </summary>
        internal static string SUBTRACTION {
            get {
                return ResourceManager.GetString("SUBTRACTION", resourceCulture);
            }
        }
    }
}
